name: Eslint test

on: [push, pull_request]

jobs:

  Eslint:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17.1'
          cache: 'npm'
      - run: npm ci
      - run: npm run eslint

  API:

    needs: Eslint

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17.1'
          cache: 'npm'
      - run: npm ci
      - run: npm run newman
