name: Eslint test

on: [push, pull_request]

jobs:

  Eslint:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17.1'
          cache: 'npm'
      - run: npm ci
      - run: npm run eslint

  API:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17.1'
          cache: 'npm'

      - uses: matt-ball/newman-action@master
        with:
          apiKey: ${{ secrets.API_TOKEN }}
          collection: ./API/Todoist_API_collection.json
          environment: ./API/Todoist_API_environment.json
        
      - run: npm ci
      - run: npm run newman
