name: Eslint test

on: [push, pull_request]

jobs:

  Eslint:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17.1'
          cache: 'npm'
      - run: npm ci
      - run: npm run eslint

  API:

    runs-on: windows-latest
    env:
      API_TOKEN: ${{ secrets.API_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17.1'
          cache: 'npm'
      - run: npm ci
      - run: newman run ./API/Todoist_API_collection.json --env-var API_TOKEN=$API_TOKEN --insecure
